#!/usr/bin/env python

import rospy
from std_msgs.msg import Float32MultiArray
from villa_sound_localization.plotmusic import PlotMusic
from pylab import rcParams
rcParams['figure.figsize'] = 20, 20

rospy.init_node('visualize', anonymous=True)

# Setup subscriber
plot_music = None
def musicspec_cb(spec):
    global plot_music
    if plot_music is None:
        plot_music = PlotMusic()
    plot_music.calculate(spec)
musicspec = rospy.Subscriber('/villa/sound_localization/debug/musicspectrum', Float32MultiArray, musicspec_cb)

rospy.spin()
